---

- name: run setup module
  setup:

- include_role:
    name: "{{ ovirt_guest_agent_role }}"
  when: target_ovirt | bool

- include_role:
    name: "{{ virtualbox_guest_additions_role }}"
  when: "'VirtualBox' in ansible_product_name"

- include_tasks: disable-auto-logon.yml

- include_tasks: updates.yml
  when:
    - install_updates | bool
    - "'Windows Server 2012' not in ansible_distribution"

- include_tasks: updates-powershell.yml
  when:
    - install_updates | bool
    - "'Windows Server 2012' in ansible_distribution"

- include_role:
    name: "{{ vmware_tools_role }}"
  when: "'VMware' in ansible_product_name"

- include_tasks: startup.yml

- include_tasks: policy.yml

- include_tasks: power.yml
  when:
    - "'Windows 10' in ansible_distribution"

- include_tasks: enable-rdp.yml

- include_tasks: cloudbase-init.yml
  when:
    - "'VMware' not in ansible_product_name"
    - "'VirtualBox' not in ansible_product_name"
    - not target_ovirt | bool

- include_tasks: remove-apps-alt.yml
  when:
    - remove_apps | bool
    - "'Windows 10' in ansible_distribution"

- include_role:
    name: "{{ ec2_ena_driver_role }}"
  when: target_ec2 | bool

- include_tasks: clean-up-components.yml
  when: clean_up_components | bool

- include_tasks: clean-up.yml

- include_tasks: sysprep.yml

- include_tasks: compact.yml